-- Registers a Muxlet workspace, plus the declarative conditions/actions/theme
-- its rules and layout depend on, as static, built-in Lua source.
-- Generated by `mux workspace export fed2-tools`; re-run after
-- changing the layout/rules in-game and re-saving with `mux workspace save fed2-tools`.

-- Conditions used by this workspace
Mux.createDeclarativeCondition({
    cond = {
        path = "gmcp.room.info.players",
        type = "gmcp_exists"
    },
    id = "RoomHasPlayers",
    label = "RoomHasPlayers"
})
Mux.createDeclarativeCondition({
    cond = {
        path = "gmcp.room.info.flags",
        type = "gmcp_contains",
        values = "exchange"
    },
    id = "RoomIsExchange",
    label = "RoomIsExchange"
})

Mux.registerWorkspace("fed2-tools", {
    floatingPanes = {
        {
            activeContent = "fed2_local_players",
            anchor = {
                alongV = 36.950000000001,
                v = {
                    myEdge = "right",
                    ref = "output",
                    targetEdge = "right"
                }
            },
            anchorable = true,
            atAnchor = true,
            closeable = false,
            contentState = {},
            contentable = false,
            convertible = false,
            floatH = 86,
            floatW = 155,
            floatX = 1890,
            floatY = 94,
            floating = true,
            id = "pane_6",
            mainConsoleHost = false,
            name = "Local Players",
            nameAlign = "center",
            propertiesButton = false,
            renamable = false,
            resizable = false,
            rules = {
                {
                    act = "mux.showSelf",
                    actElse = "mux.hideSelf",
                    cond = {
                        ref = "RoomHasPlayers"
                    },
                    enabled = true,
                    id = "r2"
                }
            },
            showAnchorElement = false,
            showTitlebar = true,
            type = "pane",
            zoomable = false
        }
    },
    name = "fed2-tools",
    paneSpace = {
        id = "screen",
        root = {
            a = {
                a = {
                    a = {
                        activeTabName = "Who",
                        anchorable = true,
                        bordered = false,
                        closeable = false,
                        contentable = false,
                        convertible = false,
                        id = "pane_2",
                        mainConsoleHost = false,
                        minimizable = false,
                        movable = false,
                        name = "LeftTop",
                        nameAlign = "center",
                        renamable = false,
                        showTitlebar = false,
                        splittable = false,
                        swappable = false,
                        tabs = {
                            {
                                _activeContent = "fed2_who",
                                closeable = false,
                                contentState = {},
                                contentable = false,
                                movable = true,
                                name = "Who",
                                nameAlign = "center",
                                propertiesButton = false,
                                renamable = false
                            },
                            {
                                closeable = true,
                                contentable = true,
                                movable = true,
                                name = "Exchange",
                                nameAlign = "center",
                                renamable = false,
                                rules = {
                                    {
                                        act = "mux.showSelf",
                                        actElse = "mux.hideSelf",
                                        cond = {
                                            ref = "RoomIsExchange"
                                        },
                                        enabled = true,
                                        id = "r1"
                                    }
                                },
                                visible = false
                            }
                        },
                        tabsLocked = true,
                        type = "pane",
                        zoomable = false
                    },
                    b = {
                        activeTabName = "Chat",
                        anchorable = true,
                        bordered = false,
                        closeable = false,
                        contentable = false,
                        convertible = false,
                        id = "pane_4",
                        mainConsoleHost = false,
                        movable = false,
                        name = "LeftBottom",
                        nameAlign = "center",
                        renamable = false,
                        showTitlebar = false,
                        splittable = false,
                        swappable = false,
                        tabs = {
                            {
                                _activeContent = "fed2_chat",
                                closeable = false,
                                contentState = {
                                    filterIdx = 1,
                                    showTs = false
                                },
                                contentable = false,
                                movable = true,
                                name = "Chat",
                                nameAlign = "center",
                                propertiesButton = false,
                                renamable = false
                            }
                        },
                        tabsLocked = true,
                        type = "pane"
                    },
                    direction = "v",
                    ratio = 0.5,
                    type = "split"
                },
                b = {
                    a = {
                        activeContent = "fed2_player_info",
                        anchorable = true,
                        closeable = false,
                        contentState = {},
                        contentable = false,
                        convertible = false,
                        id = "pane_3",
                        mainConsoleHost = false,
                        movable = false,
                        name = "Top",
                        nameAlign = "center",
                        renamable = false,
                        showTitlebar = false,
                        splittable = false,
                        swappable = false,
                        type = "pane",
                        zoomable = false
                    },
                    b = {
                        activeContent = "mux_console",
                        addable = false,
                        anchorable = true,
                        bordered = false,
                        closeable = false,
                        contentable = false,
                        convertible = false,
                        id = "output",
                        lockSnapshot = {
                            closeable = false,
                            convertible = false,
                            movable = true
                        },
                        mainConsoleHost = true,
                        minimizable = false,
                        movable = false,
                        name = "Federation 2 Community Edition",
                        nameAlign = "center",
                        propertiesButton = false,
                        renamable = false,
                        showTitlebar = true,
                        splittable = false,
                        swappable = false,
                        type = "pane"
                    },
                    direction = "v",
                    ratio = 0.040915972747918,
                    type = "split"
                },
                direction = "h",
                ratio = 0.25073457394711,
                type = "split"
            },
            b = {
                a = {
                    activeTabName = "Map",
                    anchorable = true,
                    bordered = false,
                    closeable = false,
                    contentable = false,
                    convertible = false,
                    id = "pane_1",
                    mainConsoleHost = false,
                    minimizable = false,
                    movable = false,
                    name = "RightTop",
                    nameAlign = "center",
                    renamable = false,
                    showTitlebar = false,
                    splittable = false,
                    swappable = false,
                    tabs = {
                        {
                            _activeContent = "fed2_map",
                            closeable = false,
                            contentable = false,
                            movable = true,
                            name = "Map",
                            nameAlign = "center",
                            propertiesButton = false,
                            renamable = false
                        }
                    },
                    tabsLocked = true,
                    type = "pane",
                    zoomable = false
                },
                b = {
                    activeTabName = "Company",
                    anchorable = true,
                    bordered = false,
                    closeable = false,
                    contentable = false,
                    convertible = false,
                    id = "pane_5",
                    mainConsoleHost = false,
                    minimizable = false,
                    movable = false,
                    name = "RightBottom",
                    nameAlign = "center",
                    renamable = false,
                    showTitlebar = true,
                    splittable = false,
                    swappable = false,
                    tabs = {
                        {
                            _activeContent = "fed2_hauling_jobs",
                            closeable = true,
                            contentState = {},
                            contentable = true,
                            movable = true,
                            name = "Hauling",
                            nameAlign = "center",
                            renamable = false
                        },
                        {
                            _activeContent = "fed2_price_checker",
                            closeable = true,
                            contentState = {
                                selectedCommodity = "Alloys"
                            },
                            contentable = true,
                            movable = true,
                            name = "Price Checker",
                            nameAlign = "center",
                            renamable = false
                        },
                        {
                            closeable = false,
                            contentable = true,
                            movable = true,
                            name = "Company",
                            nameAlign = "center",
                            renamable = false
                        }
                    },
                    type = "pane",
                    zoomable = false
                },
                direction = "v",
                ratio = 0.5,
                type = "split"
            },
            direction = "h",
            ratio = 0.79976535001955,
            type = "split"
        },
        size = "20%",
        zone = "screen"
    },
    theme = "dark"
})
